title: 'Data and health '
tagline: A brand new course on Learning Lab
description: How is the big data realistically going to revolutionise our healthcare?
template:
  repo: data-and-health-template
  name: data-and-health
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
